/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GetResponse {
  status: number
  body: string
  setCookieHeaders: Array<string>
}
export declare function httpGet(url: string, headers: Record<string, string>, timeoutSec?: number | undefined | null, proxyUrl?: string | undefined | null): Promise<unknown>
export interface PostResponse {
  status: number
  body: string
}
export declare function httpPost(url: string, headers: Record<string, string>, body: string, timeoutSec?: number | undefined | null, proxyUrl?: string | undefined | null): Promise<unknown>
export interface StreamMeta {
  status: number
  headers: Record<string, string>
  setCookieHeaders: Array<string>
}
/**
 * Streaming POST: sends the request, returns metadata immediately,
 * then pushes body chunks via the `on_chunk(err?, chunk?)` callback.
 *
 * JS signature:
 *   httpPostStream(url, headers, body, onChunk, proxyUrl?) → Promise<StreamMeta>
 *
 * onChunk(null, Buffer)  — data chunk
 * onChunk(null, null)    — stream ended
 * onChunk(Error, null)   — stream error
 */
export declare function httpPostStream(url: string, headers: Record<string, string>, body: string, onChunk: (arg: Buffer | undefined | null) => any, proxyUrl?: string | undefined | null): Promise<unknown>
